apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: myapp

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/mongodb-pv
