name: Build, Test and Publish
run-name: build-test-publish

on:
  push:
    branches-ignore:
      - main
      - staging

  pull_request:
    branches:
      - main
      - staging
    types:
      - closed

  workflow_dispatch:
    inputs:
      tag:
        description: "Docker tag"
        type: string
        required: false
        default: "0.0.1"

env:
  DOCKER_TAG: 0.0.1
  SERVER_IMAGE: express-k8s
  CLIENT_IMAGE: react-k8s

jobs:
  Test-Client:
    uses: ./.github/workflows/test_build_client.yaml
    with:
      client-input: "Test and build the client"

  Test-Server:
    uses: ./.github/workflows/test_build_server.yaml
    with:
      server-input: "Test and build the server"

  publish-server:
    name: build and publish server image
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: kariukiantony/${{env.SERVER_IMAGE}}:${{env.DOCKER_TAG}}

  publish-client:
    name: build and publish client image
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: kariukiantony/${{env.CLIENT_IMAGE}}:${{env.DOCKER_TAG}}
